name: Matrix-Workflow
on: [push, workflow_dispatch]
jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: ["gradle:6-jdk8", "gradle:6-jdk11", "gradle:6-jdk17"]
    container:
      image: ${{ matrix.containers }}
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh

    
      
